apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: op-scim-bridge
  labels: &ScimDeploymentLabels
    app.kubernetes.io/name: {{ .Values.APP_INSTANCE_NAME }}
    app.kubernetes.io/component: op-scim-bridge
spec:
  selector:
    matchLabels: *ScimDeploymentLabels
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *ScimDeploymentLabels
    spec:
      containers:
      - name: op-scim-bridge
        image: {{ .Values.IMAGE_OP_SCIM }}
        imagePullPolicy: Always
        command: ["/op-scim/op-scim"]
        args: ["--redis-host={{ .Values.APP_INSTANCE_NAME }}-redis-svc", "--session={{ .Values.scimsessionPath }}", "--port=8080"]
        env:
        - name: "update"
          value: "1"
        - name: OP_DOMAIN
          value: {{ .Values.OP_ACCOUNT_DOMAIN }}
        - name: OP_ONE_CLICK
          value: "true"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - name: {{ .Values.APP_INSTANCE_NAME }}-scimsession
          mountPath: "/secret"
          readOnly: false
      volumes:
      - name: {{ .Values.APP_INSTANCE_NAME }}-scimsession
        persistentVolumeClaim:
          claimName: {{ .Values.APP_INSTANCE_NAME }}-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_INSTANCE_NAME }}-bridge-svc
  labels:
    app.kubernetes.io/name: {{ .Values.APP_INSTANCE_NAME }}
    app.kubernetes.io/component: op-scim-bridge
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: scim-bridge-https-port
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: {{ .Values.APP_INSTANCE_NAME }}
    app.kubernetes.io/component: op-scim-bridge
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.APP_INSTANCE_NAME }}-pvc
  labels:
    app.kubernetes.io/name: {{ .Values.APP_INSTANCE_NAME }}
    app.kubernetes.io/component: op-scim-bridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: standard