apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.APP_INSTANCE_NAME }}-redis
  labels: &RedisDeploymentLabels
    app.kubernetes.io/name: {{ .Values.APP_INSTANCE_NAME }}
    app.kubernetes.io/component: op-scim-bridge-redis
spec:
  selector:
    matchLabels: *RedisDeploymentLabels
  replicas: 1
  template:
    metadata:
      labels: *RedisDeploymentLabels
    spec:
      containers:
      - name: redis
        image: {{ .Values.IMAGE_REDIS }}
        imagePullPolicy: Always
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_INSTANCE_NAME }}-redis-svc
  labels:
    app.kubernetes.io/name: {{ .Values.APP_INSTANCE_NAME }}
    app.kubernetes.io/component: op-scim-bridge-redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app.kubernetes.io/name: {{ .Values.APP_INSTANCE_NAME }}
    app.kubernetes.io/component: op-scim-bridge-redis
  clusterIP: None