apiVersion: v1
kind: Pod
metadata:
  name: "${APP_INSTANCE_NAME}-tester"
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  serviceAccountName: ${APP_INSTANCE_NAME}-deployer-sa
  containers:
  - name: tester
    image: "{{ .Values.testerImage }}"
    command: ["sh"]
    args: ["/tester/run.sh"]
    env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: APP_INSTANCE_NAME
        value: ${APP_INSTANCE_NAME}
    volumeMounts:
    - name: config-volume
      mountPath: /tester
  restartPolicy: Never
  volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-test"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP_INSTANCE_NAME}-tester"
  labels:
    app.kubernetes.io/name: "${APP_INSTANCE_NAME}"
  annotations:
    marketplace.cloud.google.com/verification: test
data:
  run.sh: |-
    set -x
    endpoint="http://{{ .Release.Name }}"
    echo GET $endpoint
    http_status_code=$(curl -o /dev/null -s -w "%{http_code}\n" $endpoint)
    echo "Expected http status code: 200"
    echo "Actual http status code: $http_status_code"
    if [[ "$http_status_code" == "200" ]]; then
      echo SUCCESS
    else
      echo FAILURE
      exit 1
    fi
