apiVersion: v2
name: op-scim-bridge-mp
description: 1Password SCIM bridge
version: 1.0.0 # not used in GCP
keywords:
  - "azure active directory"
  - "okta"
  - "provisioning"
  - "SCIM"
home: https://support.1password.com/scim
maintainers:
  - name: 1Password Platform Team
    email: support+scim@1password.com
icon: https://1password.com/img/logo-v1.svg
sources:
  - https://app-updates.agilebits.com/product_history/SCIM
# appVersion should match the value of publishedVersion in the schema.yaml
appVersion: "2.8.4"
dependencies:
  - name: op-scim-bridge
    version: ~2
    repository: https://1password.github.io/op-scim-helm/
    condition: redis.enabled
  - name: common
    version: ~1
    repository: https://charts.bitnami.com/bitnami
