# define values to override those defined in subcharts (dependencies); see https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

# see https://github.com/1Password/op-scim-helm/blob/main/charts/op-scim-bridge/values.yaml for details
# scim:

# see https://github.com/bitnami/charts/tree/master/bitnami/redis for details
# redis:

# note that this file cannot be empty, hence the placeholder value; see https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/issues/479
placeholder: {}
