# define values to override those defined in subcharts (dependencies); see https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
# op-scim-bridge:
  # see https://github.com/1Password/op-scim-helm/blob/main/charts/op-scim-bridge/values.yaml for details
  # scim:
  # see https://app-catalog.vmware.com/bitnami/releases/85e9f584-8363-4bdd-96a2-97a2b82c3f08 for details
  # redis:

# nameOverride needs to be set to ensure that the public IP reference defined in application.yaml works as expected;
# otherwise the chart name "op-scim-bridge-mp" is used instead and the end result is "Referenced object not found"
# is shown in the GCP console instead of the external IP of the service
nameOverride: op-scim-bridge
