# use this to override upstream values
# note that this file cannot be empty; see https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/issues/479

# see https://github.com/1Password/op-scim-helm/blob/main/charts/op-scim-bridge/values.yaml for details
scim: {}

# see https://github.com/bitnami/charts/tree/master/bitnami/redis for details
redis: {}
