# define values to override those defined in subcharts (dependencies); see https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

# see https://github.com/1Password/op-scim-helm/blob/main/charts/op-scim-bridge/values.yaml for details
# scim:

# see https://github.com/bitnami/charts/tree/master/bitnami/redis for details
# redis:
