apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deployer-cleanup # deletes stale deployers to improve upgradeability of the SCIM bridge
spec:
  schedule: "*/1 * * * *" # once a minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl-runner
            image: bitnami/kubectl
            command: ["bash", "-c", "if [[ `kubectl get pods -n {{ .Values.namespace }} | grep -i deployer | awk '$2 ~ 1/1' | awk '{print $1}'` ]]; then sleep 20 && kubectl delete jobs -n {{ .Values.namespace }} $(kubectl get jobs -n {{ .Values.namespace }} | grep -i deployer | awk '$2 ~ 1/1' | awk '{print $1}'); fi"]
          restartPolicy: Never
