apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Values.name }}-cleanup" # deletes stale deployers to improve upgradeability of the SCIM bridge
  namespace: {{ .Values.namespace }}
  labels: &CronLabels
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: cleanup
spec:
  schedule: "*/1 * * * *" # once a minute
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels: *CronLabels
        spec:
          serviceAccountName: {{ .Values.name }}-serviceaccount
          containers:
          - name: kubectl-runner
            image: bitnami/kubectl
            volumeMounts:
            - name: config-volume
              mountPath: /cleanup
            command: ["/bin/bash"]
            args: ["/cleanup/delete-deployer.sh"]
          restartPolicy: Never
          volumes:
          - name: config-volume
            configMap:
              name: "{{ .Values.name }}-cleanup-script"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-cleanup-script"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.name }}"
    app.kubernetes.io/component: cleanup-script
data:
    delete-deployer.sh: |-
      set -e
      deployer_completed=$(kubectl get jobs -n {{ .Values.namespace }} | awk '$1 ~ /{{ .Values.name }}-deployer/ && $2 ~ /1.*1/ { print $1 }' 2>/dev/null) # determine if the deployer is running AND complete
      echo "checking for deployer"
      if [[ "$deployer_completed" ]]; then
        echo "deployer detected, deleting"
        kubectl delete jobs -n {{ .Values.namespace }} $deployer_completed 2>/dev/null; # delete the job with the correct name
      else
        echo "deployer not detected, skipping"
      fi
      exit 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-serviceaccount
  namespace: {{ .Values.namespace }}
  labels: &CronLabels
    app.kubernetes.io/name: "{{ .Values.name }}"
    app.kubernetes.io/component: cleanup
rules:
  - apiGroups: ["", "batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-serviceaccount
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-serviceaccount
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}-serviceaccount
