apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Values.name }}-cleanup" # deletes stale deployers to improve upgradeability of the SCIM bridge
spec:
  schedule: "*/1 * * * *" # once a minute
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl-runner
            image: bitnami/kubectl
            command: ["bash", "-c", "if kubectl get jobs -n {{ .Values.namespace }} | awk '$1 ~ /{{ .Values.name }}-deployer/ && $2 ~ 1/1 { print $1 }' 2>/dev/null; then kubectl delete jobs -n {{ .Values.namespace }} $(kubectl get jobs -n {{ .Values.namespace }} | awk '$1 ~ /{{ .Values.name }}-deployer/ && $2 ~ 1/1 {print $1}' 2>/dev/null) 2>/dev/null; fi; exit 0"]
          restartPolicy: Never
