apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-op-scim-bridge
  namespace: {{ .Values.namespace }}
  labels: &ScimDeploymentLabels
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: op-scim-bridge
    app: {{ .Values.name }}-op-scim-bridge
spec:
  selector:
    matchLabels: *ScimDeploymentLabels
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *ScimDeploymentLabels
    spec:
      volumes:
      - name: {{ .Values.name }}-scimsession
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-op-scim-bridge-pvc
      initContainers:
      - name: scimuser-permissions
        image: alpine:3.15
        command: ["/bin/sh", "-c"]
        args: ["mkdir -p {{ .Values.scim.filePath }}/{{ .Values.scim.userName }} && chown -R {{ .Values.scim.userId }} {{ .Values.scim.filePath }}/{{ .Values.scim.userName }}"]
        volumeMounts:
        - mountPath: "{{ .Values.scim.filePath }}"
          name: {{ .Values.name }}-scimsession
      containers:
      - name: op-scim-bridge
        image: {{ .Values.bridge.image.repository }}:{{ .Values.bridge.image.tag }}
        imagePullPolicy: Always
        command: ["/op-scim/op-scim"]
        resources:
          requests:
            cpu: 125m
            memory: 256M
          limits:
            cpu: 250m
            memory: 512M
        env:
        - name: "OP_PORT"
          value: "8080"
        - name: "OP_SESSION"
          value: "{{ .Values.scim.filePath }}/{{ .Values.scim.userName }}/scimsession"
        - name: "OP_WORKSPACE_SETTINGS"
          value: "{{ .Values.scim.filePath }}/{{ .Values.scim.userName }}/workspace-settings.json"
        - name: "OP_WORKSPACE_CREDENTIALS"
          value: "{{ .Values.scim.filePath }}/{{ .Values.scim.userName }}/workspace-credentials.json"
        - name: "OP_REDIS_URL"
          value: "redis://{{ .Values.name }}-op-scim-redis-svc:6379"
        - name: "OP_ONE_CLICK"
          value: "true"
        - name: "OP_DOMAIN"
          value: "{{ .Values.accountDomain }}"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - name: {{ .Values.name }}-scimsession
          mountPath: "/home"
