apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-op-scim-bridge-pvc
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: op-scim-bridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: standard
