apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-bridge-svc
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: op-scim-bridge
spec:
  ports:
  - name: scim-bridge-http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: scim-bridge-https-port
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: op-scim-bridge
  type: LoadBalancer
