apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-op-scim-bridge-svc
  namespace: {{ .Values.namespace }}
  labels: &OpScimBridgeServiceLabels
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: op-scim-bridge
  annotations:
    cloud.google.com/neg: '{"ingress" : true}'
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  ports:
  - name: scim-bridge-http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: scim-bridge-https-port
    port: 443
    protocol: TCP
    targetPort: 8443
  selector: *OpScimBridgeServiceLabels
  type: LoadBalancer
