apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}-op-scim-redis
  namespace: {{ .Values.namespace }}
  labels: &RedisDeploymentLabels
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: op-scim-redis
spec:
  selector:
    matchLabels: *RedisDeploymentLabels
  replicas: 1
  serviceName: {{ .Values.name }}-op-scim-redis
  template:
    metadata:
      labels: *RedisDeploymentLabels
    spec:
      containers:
      - name: op-scim-redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 125m
            memory: 256M
          limits:
            cpu: 250m
            memory: 512M
        env:
        - name: "REDIS_ARGS"
          value: "--maxmemory 256mb --maxmemory-policy volatile-lru"
        ports:
        - containerPort: 6379
