x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  # publishedVersion should match the value of appVersion in the Chart.yaml
  publishedVersion: "2.5.0"
  publishedVersionMetadata:
    releaseNote: >-
      Refer to the SCIM bridge release notes.

      https://app-updates.agilebits.com/product_history/SCIM
    releaseTypes:
      - Feature
    recommended: true
  clusterConstraints:
    assistedClusterCreation:
      type: STRICT
      gke:
        nodePool:
          - numNodes: 2
            machineType: e2-small
            imageType: COS_CONTAINERD

  images:
    "":
      properties:
        bridge.image.repository:
          type: REPO_WITH_REGISTRY
        bridge.image.tag:
          type: TAG
    redis:
      properties:
        redis.image.repository:
          type: REPO_WITH_REGISTRY
        redis.image.tag:
          type: TAG
  istio:
    type: UNSUPPORTED

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  accountDomain:
    title: 1Password sign-in address
    description: >-
      "Your 1Password sign-in address. For example: example.1password.com"
    type: string
    default: example.1password.com

required:
  - name
  - namespace
  - accountDomain
