x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "2.4.1"
  publishedVersionMetadata:
    releaseNote: >-
      Refer to the SCIM bridge release notes.

      https://app-updates.agilebits.com/product_history/SCIM
    releaseTypes:
      - Feature
    recommended: true
  clusterConstraints:
    assistedClusterCreation:
      type: STRICT
      gke:
        nodePool:
          - numNodes: 2
            machineType: e2-small
            imageType: COS_CONTAINERD

  images:
    "":
      properties:
        bridge.image.repository:
          type: REPO_WITH_REGISTRY
        bridge.image.tag:
          type: TAG
    redis:
      properties:
        redis.image.repository:
          type: REPO_WITH_REGISTRY
        redis.image.tag:
          type: TAG
  istio:
    type: UNSUPPORTED

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  accountDomain:
    title: 1Password sign-in address
    description: >-
      "Your 1Password sign-in address. For example: example.1password.com"
    type: string
    default: example.1password.com
  scim.serviceAccount:
    type: string
    title: Kubernetes Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: Service account to manage your Kubernetes cluster
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ["", "batch"]
                resources: ["jobs"]
                verbs: ["get", "list", "delete"]

required:
  - name
  - namespace
  - accountDomain
  - scim.serviceAccount
