x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "1.6.1"
  publishedVersionMetadata:
    releaseNote: >-
      Please see the SCIM bridge release notes.
    releaseTypes:
      - Feature
    recommended: true

  images:
    '':
      properties:
        bridge.image.repository:
          type: REPO_WITH_REGISTRY
        bridge.image.tag:
          type: TAG
    redis: 
      properties:
        redis.image.repository:
          type: REPO_WITH_REGISTRY
        redis.image.tag:
          type: TAG


properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE


required:
- name
- namespace
